#!/usr/bin/env node
// AUTO-GENERATED by skill-kit trigger compiler
// DO NOT EDIT — regenerate with: /skill-kit trigger compile
// Generated: 2026-08-28T23:45:54Z

const fs = require('fs');
const path = require('path');
const os = require('os');

function readStdin() {
  try { return fs.readFileSync(0, 'utf8'); } catch (e) { return ''; }
}
function safeParse(s) {
  try { return JSON.parse(s); } catch (e) { return {}; }
}

// Records one NDJSON line per action:script trigger invocation (2026-08-18,
// hook-monitoring plan) — the reap-orphaned-helper-procs.log that motivated
// this has no known writer script in this environment (settings.json / hooks.json
// / scheduled tasks all came up empty; likely Claude Code CLI internal), so this
// self-instrumentation is the only per-hook-name failure signal available.
// Fails open — monitoring must never break the hook it observes.
const __HOOK_STATE_DIR = path.join(os.homedir(), '.claude', 'skills', 'hook-kit', '.state');
function recordHookInvocation(entry) {
  try {
    fs.mkdirSync(__HOOK_STATE_DIR, { recursive: true });
    fs.appendFileSync(path.join(__HOOK_STATE_DIR, 'hook-invocations.ndjson'), JSON.stringify(entry) + '\n', 'utf8');
  } catch (e) { /* fail open */ }
}

const INPUT = readStdin();
const _input = safeParse(INPUT);
const TOOL_NAME = _input.tool_name || '';
const COMMAND = (_input.tool_input && _input.tool_input.command) || '';
const FILE_PATH = (_input.tool_input && (_input.tool_input.file_path || _input.tool_input.TargetFile)) || '';
const NEW_CONTENT = (_input.tool_input && (_input.tool_input.new_string || _input.tool_input.content || _input.tool_input.ReplacementContent || _input.tool_input.CodeContent)) || '';
const EXIT_CODE = process.env.EXIT_CODE || '0';

// cleanup (Stop, action=inject)
// fire once per session; if already fired, fall through to lower-priority triggers
{
  const path = require('path');
  const os = require('os');
  const __sessId = _input.session_id || (_input.transcript_path ? path.basename(_input.transcript_path, '.jsonl') : (process.env.CLAUDE_SESSION_ID || 'global'));
  const FIRE_FLAG = path.join(os.homedir(), '.claude', 'data', 'trigger-stop-' + __sessId + '-cleanup');
  if (!fs.existsSync(FIRE_FLAG)) {
    fs.mkdirSync(path.dirname(FIRE_FLAG), { recursive: true });
    fs.writeFileSync(FIRE_FLAG, '');
    console.log(JSON.stringify({
      decision: 'block',
      reason: "cleanup trigger",
      systemMessage: "Run /cleanup run. This is the pre-session-end cleanup task."
    }));
    process.exit(0);
  }
}

process.exit(0);

